#+TITLE:icons-in-terminal successful setup
Last update at: [2023-01-26 Thu 15:36]
* default
   Run official setup instruction once first.
   See: [[file:README.org]]
   Original Repo: [[https://github.com/sebastiencs/icons-in-terminal][icons-in-terminal Github Repo]]

   *Remember* to edit the [[~/.config/fontconfig/conf.d/30-icons.conf][font patch's config]] (XML).
   It is XML and you will have to manually escape char if necessary.
   Follow the instruction to comment out all lines under the fontconfig tag except the chosen font.
   
   Add a line like this if it doesn't exist yet:
   #+begin_quote xml
   <alias><family>JetBrainsMono Nerd Font</family><prefer><family>icons-in-terminal</family></prefer></alias>
   #+end_quote
   
   As of [2023-01-26 Thu] mine's is =JetBrainsMono Nerd Font=.
   
* kitty
   Kitty needs unicode range map as follows:
   #+begin_quote
   symbol_map U+E000-U+EEA0 icons-in-terminal
   #+end_quote

* font config
   Better rebuild font config cache after install:
   #+begin_src shell-script
   fc-cache -f -v
   #+end_src

* MacOS
   MacOS might have overridden some unix system calls that checks font list.
   One will need to install the patched font again with Apple's /Font Book/
   in order for applications like =kitty= to pick it up.

   #+begin_src sh :results vector
   echo
   echo count type value comment
   echo
   fc-list -v | grep icons-in-terminal | sort -V | uniq -c | sed 's/"/'\''/g' | sed -E 's/^ +//' | sed -E 's/[^a-zA-Z0-9./:()-]+/|/g' | sort
   echo
   #+end_src

   #+RESULTS:
   |-------+-----------------+-----------------------------------------------+---------|
   | count | type            | value                                         | comment |
   |-------+-----------------+-----------------------------------------------+---------|
   |     1 | family:         | icons-in-terminal                             | (s)     |
   |     1 | file:           | =${HOME}/.fonts/icons-in-terminal.ttf=          | (s)     |
   |     1 | fullname:       | icons-in-terminal                             | (s)     |
   |     1 | postscriptname: | icons-in-terminal                             | (s)     |
   |-------+-----------------+-----------------------------------------------+---------|

   open the =ttf= file to install.

   #+begin_src sh
   # try xdg-open for linux if you have it
   open ${HOME}/.fonts/icons-in-terminal.ttf
   #+end_src

   #+RESULTS:

* Emacs (=icons-in-terminal.el=)
  I used =icons-in-terminal.el=, see: https://github.com/seagle0128/icons-in-terminal.el
  
  The mapping is too old, which corresponds to =all-the-icons v4.0.1=
  + Latest version is =all-the-icons v5.0.0= as of [2023-01-26 Thu]
    + After install, please replace =icons-in-terminal-data.el= with [[file:patches/icons-in-terminal-data.el][my patched version]].
  As for =all-the-icons=, one should NOT install latest via Melpa but rather
  go the =4.0.1= version, manually or any preferred way.
  This allow the package to work with fewer patches.
  
** Using in a Terminal
   Since most packages that supports fancy icons uses =all-the-icons=, and that
   =icons-in-terminal='s API is modelling agaist it, we can use those packages
   by aliasing alls to functions to those in =icons-in-terminal=.
    
   As such:
   #+begin_quote emacs-lisp
   (add-to-list 'load-path "~/.emacs.d/all-the-icons.el-4.0.1/")
   (require 'all-the-icons)
   (with-eval-after-load 'all-the-icons
     (defalias #'all-the-icons-insert #'icons-in-terminal-insert)
     (defalias #'all-the-icons-insert-faicon #'icons-in-terminal-insert-faicon)
     (defalias #'all-the-icons-insert-fileicon #'icons-in-terminal-insert-fileicon)
     (defalias #'all-the-icons-insert-material #'icons-in-terminal-insert-material)
     (defalias #'all-the-icons-insert-octicon #'icons-in-terminal-insert-octicon)
     (defalias #'all-the-icons-insert-wicon #'icons-in-terminal-insert-wicon)
     (defalias #'all-the-icons-insert-devicon #'icons-in-terminal-insert)
     (defalias #'all-the-icons-insert-alltheicon #'icons-in-terminal-insert)

     (defalias #'all-the-icons-icon-for-dir #'icons-in-terminal-icon-for-dir)
     (defalias #'all-the-icons-icon-for-file #'icons-in-terminal-icon-for-file)
     (defalias #'all-the-icons-icon-for-mode #'icons-in-terminal-icon-for-mode)
     (defalias #'all-the-icons-icon-for-url #'icons-in-terminal-icon-for-url)
    
     (defalias #'all-the-icons-icon-family #'icons-in-terminal-icon-family)
     (defalias #'all-the-icons-icon-family-for-buffer #'icons-in-terminal-icon-family-for-buffer)
     (defalias #'all-the-icons-icon-family-for-file #'icons-in-terminal-icon-family-for-file)
     (defalias #'all-the-icons-icon-family-for-mode #'icons-in-terminal-icon-family-for-mode)
     (defalias #'all-the-icons-icon-for-buffer #'icons-in-terminal-icon-for-buffer)
    
     (defalias #'all-the-icons-faicon #'icons-in-terminal-faicon)
     (defalias #'all-the-icons-octicon #'icons-in-terminal-octicon)
     (defalias #'all-the-icons-fileicon #'icons-in-terminal-fileicon)
     (defalias #'all-the-icons-material #'icons-in-terminal-material)
     (defalias #'all-the-icons-wicon #'icons-in-terminal-wicon)
     ;; (defalias #'all-the-icons-devicon #'icons-in-terminal-fileicon)
     ;; (defalias #'all-the-icons-alltheicon #'icons-in-terminal-fileicon)

     (defalias 'all-the-icons-default-adjust 'icons-in-terminal-default-adjust)
     (defalias 'all-the-icons-color-icons 'icons-in-terminal-color-icons)
     (defalias 'all-the-icons-scale-factor 'icons-in-terminal-scale-factor)
     (defalias 'all-the-icons-icon-alist 'icons-in-terminal-icon-alist)
     (defalias 'all-the-icons-dir-icon-alist 'icons-in-terminal-dir-icon-alist)
     (defalias 'all-the-icons-weather-icon-alist 'icons-in-terminal-weather-icon-alist)
     )
     
   ;; Edit config at ~/.config/fontconfig/conf.d/30-icons.conf
   (add-to-list 'load-path "~/.emacs.d/icons-in-terminal.el/")
   (require 'icons-in-terminal)
   (with-eval-after-load 'treemacs
     (require 'treemacs-all-the-icons)
     (treemacs-load-theme "all-the-icons"))
   #+end_quote
 
** Patching packages
*** treemacs-all-the-icons
    Please use my patched version of [[file:patches/treemacs-all-the-icons.el][treemacs-all-the-icons.el]]
    
    Some packages uses the latest mapping which may yield bad results.
    Change the configs (i.e. icon names) in those cases.

    + Remember to do =emacs-lisp-byte-compile=
*** all-the-icons-dired-mode
    No need to patch (^_^)
* Future work [2023-01-26 Thu 15:36]
  [2023-10-31 Tue 15:02]
  Please do not use this for Emacs, use nerd-icons
  https://github.com/rainstormstudio/nerd-icons.el
  
  + update fonts of =icons-in-terminal= for =all-the-icons v5.0.0=
  + bump mapping and structure of =icons-in-terminal.el= to follow =all-the-icons v5.0.0=
    
